name: Render Keep-Alive Ping

on:
  schedule:
    # runs every 14 minutes to prevent render from sleeping
    - cron: '*/14 * * * *'
  workflow_dispatch: # allows to run it manually (not to wait 14 min) 

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl -sS --max-time 120 https://greenifier.onrender.com/ > /dev/null
          echo "ping sent"
